### ISSUE TITLE
doplnění verzí u webfóra

### ISSUE THREAD

**Issue by nesnera** [xbmc-kodi-cz/repository.xbmc-kodi.cz#2]
Při prvních kontaktech s Kodi jsem netušil, že existují Leia, Matrix, ..  Tudíž jsem údaje v závorkách [popisu](https://repo.xbmc-kodi.cz/) považoval za kódová označení těch zipů. Bylo by možné pro jednoznačnost/návodnost texty upravit takto?:

- repository.xbmc-kodi.cz-1.1.2.zip (Leia) > repository.xbmc-kodi.cz-1.1.2.zip pro Kodi v18 (Leia)
- repository.xbmc-kodi.cz-1.2.0.zip (Matrix) > repository.xbmc-kodi.cz-1.2.0.zip pro Kodi v19 (Matrix)

(odpovídalo by to značení z Kodi Wiki - https://kodi.wiki/view/Releases)

**Comment by wombat01** [comment]
Ok, doplněno.
